### ISSUE TITLE
is iteminfo.lua suppose to be a .lub file type?

### ISSUE THREAD

**Issue by davidmgrantham** [llchrisll/ROenglishRE#38]

**Comment by llchrisll** [comment]
Nope, also it's itemInfo_EN.lua, I could rename it to itemInfo_EN.lub, but an .lub file is an compiled lua file, which makes it smaller in size and unreadable without an decoder.
Also because I renamed it to _EN, which prevents kRO from overwriting it, you need to patch your client to read that instead anyway.
