### ISSUE TITLE
ClientGenerator.bat skips navi_picknpc, navi_scroll; NEMO Add custom lua support [Navigation]

### ISSUE THREAD

**Issue by fzuviria** [llchrisll/ROenglishRE#66]
Hi Chris, great work!

First time user, doing a client as simple as possible.

I had lua errors regarding navi_picknpc and navi_scroll.

In the end I resolved the issue by manually adding
- navi_picknpc_krpri.lub
- navi_picknpc_krsak.lub
- navi_scroll_krpri.lub
- navi_scroll_krsak.lub
from ROenglishRE\Addons\Navigation Legacy to my GRF

this files are ommited by the ClientGenerator.bat

Maybe the new and intended use is to use custom lua support navigation with the CLSGenerator.bat, *however*, I was not able to patch Ragexe to support this. According to http://nemo.herc.ws/patches/ --> http://nemo.herc.ws/patches/AddCLSNavi/#success-clients the Patch 'Add custom lua support [Navigation]' fails on 100% of the clients ever tested by NEMO. This patch was submitted by you (thank youuuu) so I might as well bring this up here.

Best regards!!!

**Comment by llchrisll** [comment]
They are ommited by an reason, because the Navigation Legacy files are pretty outdated compared to kRO.
~2019 entries are in there.
Since I modified the navi_f_kr.lub and navi_f_sak.lub respectively ages ago to load and use my custom lua file (System/Navi_Data_EN.lua) which holds only entries for translation.
I didn't bother with navigation files anymore, because it was and is a pain to sync.

In case you didn't read the documenation:
https://llchrisll.github.io/ROTPDocs/addons/#nemo
I explained that 4144 (NEMO) still has to update that patch make it work on his side.
In WARP it works fine.
