### ISSUE TITLE
itemInfo_EN.lua some problem

### ISSUE THREAD

**Issue by idk-whoami** [llchrisll/ROenglishRE#83]
the EffectID function is missing
when monsters that drop items do not display effects

AND 

the costume function is missing
when moving costume items to storage, not in the costume category

**Comment by llchrisll** [comment]
Not sure what you are talking about...
https://github.com/llchrisll/ROenglishRE/blob/cbf92e8d6c09706561cecbfee42ea54650625c8b/Translation/Compatibility/2018-06-20/Renewal/System/LuaFiles514/itemInfo_f.lua#L44

Please remember, since #55, I changed the default version of the project back to 2015-10-29, where the iteminfo doesn't work with those additional arguments. Also with #67 the function itself was split to the file above, resutling only in one iteminfo to change unlike before where it was 3 files.

**Comment by idk-whoami** [comment]
OH sorry and thanks for the suggestion :)
