### ISSUE TITLE
Ongoing Quests CLS has incorrect order

### ISSUE THREAD

**Issue by neico** [llchrisll/ROenglishRE#94]
In the function `GetOngoingQuestInfoByID` it first checks gravity's quests before checking the custom table, causing all sorts of unexpected behavior.

While we're on the topic, from my point of view it would be smarter to just merge the tables together when loading the file, ex:
```lua
dofile("SystemEN/OngoingQuests_C.lub")
dofile("SystemEN/RecommendedQuests_C.lub")

for Key, Value in pairs( QuestInfoList_C ) do
	QuestInfoList[Key] = Value
end

for Key, Value in pairs( RecommendedQuestInfoList_C ) do
	RecommendedQuestInfoList[Key] = Value
end
...
```
Then the functions don't really need to check for differences on those tables anymore, avoiding potential issues like that.

That said, ideally it would do so more gradually, so you can omit any information from `QuestInfoList_C` that you don't want to override (in case you are overriding an existing quest entry).
Maybe being able to remove an QuestID from the table would also be helpful, ex. `[1001] = {}` should result in it being removed (as `[1001] = nil` isn't really a valid option pre-lua5.4 in this case)
And referencing another QuestID entry (for duplicates) could also be introduced, ex. `[1001] = 1002`, making CLS truly powerful.

I haven't checked all the other cases in CLS where this could be of benefit,
but I'll trust some places will come to your mind when you're thinking about that, given that you've written it.

I know this is a bit more than just a strict one topic per issue, but it's what came to mind when I was looking into why the Quests were behaving so differently compared to replacing it in `OngoingQuestInfoList_True.lub` (don't ask, I'm juggling with older installations right now) using the above-mentioned merging.
If you want me to move the suggestions into a separate issue to tackle them one at a time, let me know.

**Comment by llchrisll** [comment]
Thanks for your feedback first of all.
But I wanna know what kind of behavior you are talking about, so I know what you are referring to.
I only tested with a few custom quests, which I deleted afterwards so I can't say much about it unless I have more info.

Also my lua knowledge is still basic, especially when I wrote it, I went by trail and error (run & debug) until it finally worked as I wanted it (to learn lua a bit better).
But you are right on merging the tables together, just like I did with the signboard and itemInfo tables after a bit for learning more about it, would be more efficient.

But I don't want users overwrite official quests by accident to cause other issues.
So I would still add a check for existing quests. Maybe I would make another simple table and function to insert quest entries to "overwrite" so [1001] = {} via loop, so the overwrite is intended. Might be just me and maybe less optimized, but let's see.

Not sure how referencing quests would work, didn't play with that. Also I can't think where this could be handy, in my opinion quests should be kinda unique content wise, otherwise you could just use the same quest again.

If you are more of a expert of the lua language, feel free to suggest improvements.
I will try to make adjustments to the Quests, once I have some time.
Maybe even an PR for you and others to have a look at and give me feedback on that.

Regards,
Chris

**Comment by llchrisll** [comment]
Modified with 2f251df07daeef81a6d0b7c98268cb416dc8a6ae
